name: Generate Autonomous UAV Path

on:
  schedule:
    - cron: "0 */12 * * *" # Her 12 saatte bir
  workflow_dispatch:
  push:
    branches:
    - main #  master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: generate-snake-svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark&color_snake=#00fbff&color_dots=#161b22
            dist/snake-light.svg?palette=github-light&color_snake=#00fbff&color_dots=#ebedf0

      - name: push-snake-svg-to-output-branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
